import React from 'react';
import NextLink from 'next/link';
import {
  Container,
  Box,
  Text,
  Link,
  Flex,
  Popover,
  Button,
  Badge,
  Heading,
  Separator,
} from '@modulz/design-system';
import { Logo } from './Logo';
import { HideInProd } from './HideInProd';
import { PlusIcon } from '@modulz/radix-icons';

export const Header = () => {
  const [isOpen, setIsOpen] = React.useState(false);
  const buttonRef = React.useRef<HTMLButtonElement>(null);

  return (
    <Container size="4">
      <Flex css={{ justifyContent: 'space-between' }}>
        <NextLink href="/" passHref>
          <Link css={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>
            <Box>Modulz homepage</Box>
            <Logo aria-hidden />
          </Link>
        </NextLink>

        <Flex css={{ alignItems: 'flex-start' }}>
          <Button variant="ghost">
            <Flex css={{ alignItems: 'center' }}>
              <Text size="3" as="span" css={{ color: 'gray700' }} style={{ lineHeight: 1 }}>
                Product
              </Text>
              <Box>
                <PlusIcon />
              </Box>
            </Flex>
          </Button>

          <Popover>
            <Box css={{ width: 300 }}>
              <Box>
                <Text size="3">
                  Design
                </Text>
                <Text size="3" color="gray">
                  Advanced tooling for defining scale-based design tokens.
                </Text>
              </Box>
              <Box>
                <Text size="3">
                  Prototyping
                </Text>
                <Text size="3" color="gray">
                  A visual code editor for building a component library without writing code.
                </Text>
              </Box>
              <Box>
                <Text size="3">
                  Handoff
                </Text>
                <Text size="3" color="gray">
                  A visual code editor for building a component library without writing code.
                </Text>
              </Box>
              <Box>
                <Text size="3">
                  Design Systems
                </Text>
                <Text size="3" color="gray">
                  A visual code editor for building a component library without writing code.
                </Text>
              </Box>

              <Separator />

              <a href="https://radix-ui.com" style={{ textDecoration: 'none', color: 'inherit' }}>
                <Box as="span" css={{ display: 'block', ':hover': { backgroundColor: 'gray200' } }}>
                  <Text size="3">Radix</Text>
                  <Text size="2" color="gray">
                    Our very own design system—generated by Modulz.
                  </Text>
                </Box>
              </a>
            </Box>
          </Popover>

          <Text size="3" css={{ color: 'gray700' }} style={{ lineHeight: 1 }}>
            <NextLink href="/blog" passHref>
              <Link css={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>Blog</Link>
            </NextLink>
          </Text>

          <Separator size="1" orientation="vertical" css={{ mx: 45 }} />

          <Text size="3" css={{ color: 'gray700' }}>
            <Link href="https://kickstarter.modulz.app" css={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>
              Login
            </Link>
          </Text>
        </Flex>
      </Flex>
    </Container>
  );
};
