import React from 'react';
import NextLink from 'next/link';
import { Container, Box, Grid, Heading, Button, Text, Link, Divider, Flex, AspectRatio } from '@modulz/radix';
import { BetaAccess } from '../components/BetaAccess';
import TitleAndMetaTags from '../components/TitleAndMetaTags';

const Editor = () => {
  return (
    <Box>
      <TitleAndMetaTags />

      <Box mt={6} mb={8}>
        <Container size={2}>
          <Heading size={5} mb={4} sx={{ textAlign: 'center' }}>
            The visual code editor
          </Heading>

          <Heading as="h2" size={2} weight="normal" sx={{ textAlign: 'center', color: 'gray700', lineHeight: '4' }}>
            Style your component library, from color to shadows to animations—without writing code.
          </Heading>
        </Container>
      </Box>

      <Container size={3}>
        <Flex mb={7} sx={{ justifyContent: 'space-around' }}>
          <Box sx={{ position: 'relative', width: '175px', opacity: '.5' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Panes
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
          <Box sx={{ position: 'relative', width: '175px', opacity: '.5' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Variants
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
          <Box sx={{ position: 'relative', width: '175px', opacity: '1' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Parts
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
          <Box sx={{ position: 'relative', width: '175px', opacity: '.5' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Properties
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
        </Flex>
        <img
          src="/home/editor.png"
          style={{
            display: 'block',
            maxWidth: '100%',
            boxShadow: 'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
            borderWidth: '1px',
            borderStyle: 'solid',
            borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
            borderRadius: '10px',
          }}
        />
      </Container>

      <Divider mx="auto" size={2} />

      <Box py={9}>
        <Container size={1}>
          <Text
            as="h3"
            size={2}
            mb={3}
            sx={{
              textAlign: 'center',
              fontWeight: 500,
              color: 'gray700',
              letterSpacing: '.125em',
              textTransform: 'uppercase',
            }}
          >
            Components
          </Text>
          <Heading as="h3" size={4} mb={3} sx={{ textAlign: 'center' }}>
            Kickstart your design system with premade components.
          </Heading>
          <Text
            as="p"
            size={5}
            sx={{ textAlign: 'center', color: 'gray700', lineHeight: '3' }}
          >
            Hundreds of white-label components including sliders, tabs, buttons, datepickers and more. Compose entire interfaces with free resources, generated by one of the largest design communities in the world.
          </Text>
          <Box mt={5} mb={7}>
            <Text as="span" size={4} sx={{ color: 'blue600', lineHeight: 1 }}>
              <NextLink href="/styleguide" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>Component store</Link>
              </NextLink>
            </Text>
          </Box>
        </Container>
        <Flex py="5" px="9" sx={{ alignItems: 'center', userSelect: 'none' }}>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            backgroundColor: 'gray200',
            px: '3',
            height: '6',
            fontSize: '3',
            fontWeight: '500',
            borderRadius: '2',
            mr: '8',
          }}>
            Button
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            px: '2',
            height: '4',
            fontSize: '1',
            border: '1px solid',
            borderColor: 'gray300',
            color: 'gray700',
            fontWeight: '500',
            borderRadius: '9999px',
            mr: '8',
          }}>
            Badge
          </Box>
          <Box sx={{
            backgroundColor: 'gray200',
            height: '3px',
            width: '100px',
            borderRadius: '9999px',
            position: 'relative',
            mr: '8',
          }}>
            <Box sx={{
              backgroundColor: 'gray500',
              height: '100%',
              width: '50%',
              borderRadius: '9999px',
            }}></Box>
            <Box sx={{
              backgroundColor: 'white',
              border: '1px solid',
              borderColor: 'gray100',
              boxShadow: '0 1px 2px rgba(0,0,0,.1)',
              height: '15px',
              width: '15px',
              borderRadius: '50%',
              position: 'absolute',
              left: '50%',
              marginLeft: '-7px',
              top: '-5px',
            }}></Box>
          </Box>
          <Box sx={{
            backgroundColor: 'gray200',
            height: '2',
            width: '150px',
            borderRadius: '9999px',
            position: 'relative',
            mr: '8',
          }}>
            <Box sx={{
              backgroundColor: 'gray500',
              height: '100%',
              width: '50%',
              borderRadius: '9999px 0 0 9999px',
            }}></Box>
          </Box>
          <Box sx={{
            backgroundColor: 'white',
            borderRadius: '2',
            position: 'relative',
            py: '2',
            mr: '8',
            boxShadow: '0 10px 38px -10px rgba(22,23,24,0.35), 0 10px 20px -15px rgba(22,23,24,0.2)',
          }}>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              This is a menu item
            </Box>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Second menu item
            </Box>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Menu item
            </Box>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Another menu item
            </Box>
          </Box>
          <Box sx={{
            backgroundColor: 'white',
            borderRadius: '2',
            position: 'relative',
            py: '2',
            mr: '8',
            boxShadow: '0 10px 38px -10px rgba(22,23,24,0.35), 0 10px 20px -15px rgba(22,23,24,0.2)',
          }}>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Calendar
            </Box>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Second menu item
            </Box>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Menu item
            </Box>
            <Box sx={{
              display: 'flex',
              alignItems: 'center',
              px: '6',
              height: '6',
              fontSize: '1',
            }}>
              Another menu item
            </Box>
          </Box>
          <Box sx={{
            backgroundColor: 'gray300',
            height: '3',
            width: '6',
            borderRadius: '9999px',
            mr: '8',
          }}>
            <Box sx={{
              backgroundColor: 'white',
              border: '1px solid',
              borderColor: 'gray300',
              boxShadow: '0 1px 3px rgba(0,0,0,.05)',
              height: '3',
              width: '3',
              borderRadius: '50%',
            }}></Box>
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            width: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '50%',
            mr: '8',
          }}>
            <Box sx={{
              backgroundColor: 'gray600',
              height: '9px',
              width: '9px',
              borderRadius: '50%',
            }}></Box>
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            width: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M11.467 3.72686C11.7559 3.91576 11.8369 4.30309 11.648 4.592L7.39803 11.092C7.29787 11.2452 7.1356 11.3468 6.95405 11.3699C6.77251 11.3931 6.58992 11.3355 6.4545 11.2124L3.7045 8.71243C3.44909 8.48024 3.43027 8.08496 3.66246 7.82954C3.89465 7.57413 4.28993 7.55531 4.54534 7.7875L6.75295 9.79442L10.6018 3.90793C10.7907 3.61903 11.178 3.53796 11.467 3.72686Z" fill="#282B2E"/>
            </svg>
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Avatar
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Alert
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Toast
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Card
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Input
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Code
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Select
          </Box>
          <Box sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '5',
            border: '1px solid',
            borderColor: 'gray400',
            borderRadius: '1',
            mr: '8',
          }}>
            Tooltip
          </Box>
        </Flex>
        <Container size={2}>
          <Grid
            sx={{
              gridTemplateColumns: ['repeat(1, 1fr)', 'repeat(2, 1fr)'],
              gap: 7,
            }}
          >
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ color: 'white' }}>
                Accessible
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', color: 'gray700' }}>
                Keyboard accessible. Touch events. Screen readers. Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ color: 'white' }}>
                Customisable
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', color: 'gray700' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
          </Grid>
        </Container>
      </Box>

      <Box py={9} sx={{ backgroundColor: 'hsl(210,10%,6%)' }}>
        <Container size={2}>
          <Text
            as="h3"
            size={2}
            mb={3}
            sx={{
              textAlign: 'center',
              fontWeight: 500,
              color: 'gray700',
              letterSpacing: '.125em',
              textTransform: 'uppercase',
            }}
          >
            Code export
          </Text>
          <Heading as="h3" size={4} mb={3} sx={{ textAlign: 'center', color: 'white' }}>
            The most advanced code generation. <br /> Hands down.
          </Heading>
          <Text
            as="p"
            size={5}
            sx={{ textAlign: 'center', color: 'gray600', lineHeight: '3' }}
          >
            Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
          </Text>
        </Container>
        <Container size={3}>
          <Box
            sx={{
              position: 'relative',
              height: '580px',
            }}
          >
            <Box
              sx={{
                position: 'absolute',
                width: '100%',
                top: '-160px',
              }}
            >
              <AspectRatio ratio="16:9">
                <Box
                  sx={{
                    backgroundColor: 'black',
                    height: '100%',
                    borderRadius: '10px',
                    transform: 'perspective(100em) rotateX(70deg)',
                  }}
                >
                </Box>
              </AspectRatio>
            </Box>
            <Box
              sx={{
                position: 'absolute',
                width: '100%',
                top: '70px'
              }}
            >
              <AspectRatio ratio="16:9">
                <Box
                  sx={{
                    backgroundColor: 'black',
                    height: '100%',
                    borderRadius: '10px',
                    transform: 'perspective(100em) rotateX(70deg)',
                  }}
                >
                </Box>
              </AspectRatio>
            </Box>
          </Box>
          <Grid
            sx={{
              gridTemplateColumns: ['repeat(1, 1fr)', 'repeat(2, 1fr)', 'repeat(4, 1fr)'],
              gap: 5,
            }}
          >
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Powered by React
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Configurable
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Extendible
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Popular libraries
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Built on top of Styled System Core. Styled-components. Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
          </Grid>
        </Container>
      </Box>

      <Box py={9}>
        <Container size={3}>
          <Flex mt={8} sx={{ alignItems: 'center' }}>
            <Box mr={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <img
                src="/home/editor.png"
                style={{
                  display: 'block',
                  maxWidth: '100%',
                  boxShadow:
                    'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
                  borderWidth: '1px',
                  borderStyle: 'solid',
                  borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
                  borderRadius: '10px',
                }}
              />
            </Box>
            <Box ml={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <Heading as="h3" size={3} mb={3} sx={{ fontWeight: 500, letterSpacing: '-.042em' }}>
                Panes
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', letterSpacing: '-.008em' }}>
                This is going to be a bit of a thought dump, I'm not sure any of it blocks the registration itself, but
                I think it brings up a lot of questions.
              </Text>
            </Box>
          </Flex>

          <Flex mt={8} sx={{ alignItems: 'center' }}>
            <Box mr={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <img
                src="/home/editor.png"
                style={{
                  display: 'block',
                  maxWidth: '100%',
                  boxShadow:
                    'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
                  borderWidth: '1px',
                  borderStyle: 'solid',
                  borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
                  borderRadius: '10px',
                }}
              />
            </Box>
            <Box ml={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <Heading as="h3" size={3} mb={3} sx={{ fontWeight: 500, letterSpacing: '-.042em' }}>
                Transitions
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', letterSpacing: '-.008em' }}>
                This is going to be a bit of a thought dump, I'm not sure any of it blocks the registration itself, but
                I think it brings up a lot of questions.
              </Text>
            </Box>
          </Flex>

          <Flex mt={8} sx={{ alignItems: 'center' }}>
            <Box mr={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <img
                src="/home/editor.png"
                style={{
                  display: 'block',
                  maxWidth: '100%',
                  boxShadow:
                    'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
                  borderWidth: '1px',
                  borderStyle: 'solid',
                  borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
                  borderRadius: '10px',
                }}
              />
            </Box>
            <Box ml={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <Heading as="h3" size={3} mb={3} sx={{ fontWeight: 500, letterSpacing: '-.042em' }}>
                Linter
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', letterSpacing: '-.008em' }}>
                This is going to be a bit of a thought dump, I'm not sure any of it blocks the registration itself, but
                I think it brings up a lot of questions.
              </Text>
            </Box>
          </Flex>
        </Container>
      </Box>

      <Divider mx="auto" size={2} />

      <BetaAccess />
    </Box>
  );
};

export default Editor;
