import React from 'react';
import NextLink from 'next/link';
import { Container, Box, Grid, Heading, Button, Text, Link, Divider, Flex, AspectRatio } from '@modulz/radix';
import { BetaAccess } from '../components/BetaAccess';
import TitleAndMetaTags from '../components/TitleAndMetaTags';

const Editor = () => {
  return (
    <Box>
      <TitleAndMetaTags />

      <Box mt={6} mb={8}>
        <Container size={2}>
          <Heading size={5} mb={4} sx={{ textAlign: 'center' }}>
            The visual code editor
          </Heading>

          <Heading as="h2" size={2} weight="normal" sx={{ textAlign: 'center', color: 'gray700', lineHeight: '4' }}>
            Style your component library, from color to shadows to animations—without writing code.
          </Heading>
        </Container>
      </Box>

      <Container size={3}>
        <Flex mb={7} sx={{ justifyContent: 'space-around' }}>
          <Box sx={{ position: 'relative', width: '175px', opacity: '.5' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Panes
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
          <Box sx={{ position: 'relative', width: '175px', opacity: '.5' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Variants
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
          <Box sx={{ position: 'relative', width: '175px', opacity: '1' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Parts
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
          <Box sx={{ position: 'relative', width: '175px', opacity: '.5' }}>
            <Text as="p" size={2} mb={1} sx={{ letterSpacing: '0', lineHeight: '1', fontWeight: 500 }}>
              Properties
            </Text>
            <Text as="p" size={2} sx={{ letterSpacing: '0', lineHeight: '1' }}>
              Modulz is a visual code editor that empowers teams to design and develop a design system.
            </Text>
          </Box>
        </Flex>
        <img
          src="/home/editor.png"
          style={{
            display: 'block',
            maxWidth: '100%',
            boxShadow: 'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
            borderWidth: '1px',
            borderStyle: 'solid',
            borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
            borderRadius: '10px',
          }}
        />
      </Container>

      <Divider mx="auto" size={2} />

      <Box py={9} sx={{ backgroundColor: 'hsl(210,10%,9%)' }}>
        <Container size={1}>
          <Text
            as="h3"
            size={2}
            mb={3}
            sx={{
              textAlign: 'center',
              fontWeight: 500,
              color: 'gray700',
              letterSpacing: '.125em',
              textTransform: 'uppercase',
            }}
          >
            Components
          </Text>
          <Heading as="h3" size={4} mb={3} sx={{ textAlign: 'center', color: 'white' }}>
            Kickstart your design system with premade components.
          </Heading>
          <Text
            as="p"
            size={5}
            sx={{ textAlign: 'center', color: 'gray700', lineHeight: '3' }}
          >
            Hundreds of white-label components including sliders, tabs, buttons, datepickers and more. Compose entire interfaces with free resources, generated by one of the largest design communities in the world.
          </Text>
          <Box mt={5} mb={7}>
            <Text as="span" size={4} sx={{ color: 'blue600', lineHeight: 1 }}>
              <NextLink href="/styleguide" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>Component store</Link>
              </NextLink>
            </Text>
          </Box>
        </Container>
        <Button size={1}>
          Button
        </Button>
        <Container size={2}>
          <Grid
            sx={{
              gridTemplateColumns: ['repeat(1, 1fr)', 'repeat(2, 1fr)'],
              gap: 7,
            }}
          >
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ color: 'white' }}>
                Accessible
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', color: 'gray700' }}>
                Keyboard accessible. Touch events. Screen readers. Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ color: 'white' }}>
                Customisable
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', color: 'gray700' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
          </Grid>
        </Container>
      </Box>

      <Box py={9} sx={{ backgroundColor: 'hsl(210,10%,6%)' }}>
        <Container size={2}>
          <Text
            as="h3"
            size={2}
            mb={3}
            sx={{
              textAlign: 'center',
              fontWeight: 500,
              color: 'gray700',
              letterSpacing: '.125em',
              textTransform: 'uppercase',
            }}
          >
            Code export
          </Text>
          <Heading as="h3" size={4} mb={3} sx={{ textAlign: 'center', color: 'white' }}>
            The most advanced code generation. <br /> Hands down.
          </Heading>
          <Text
            as="p"
            size={5}
            sx={{ textAlign: 'center', color: 'gray600', lineHeight: '3' }}
          >
            Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
          </Text>
        </Container>
        <Container size={3}>
          <Box
            sx={{
              position: 'relative',
              height: '580px',
            }}
          >
            <Box
              sx={{
                position: 'absolute',
                width: '100%',
                top: '-160px',
              }}
            >
              <AspectRatio ratio="16:9">
                <Box
                  sx={{
                    backgroundColor: 'black',
                    height: '100%',
                    borderRadius: '10px',
                    transform: 'perspective(100em) rotateX(70deg)',
                  }}
                >
                </Box>
              </AspectRatio>
            </Box>
            <Box
              sx={{
                position: 'absolute',
                width: '100%',
                top: '70px'
              }}
            >
              <AspectRatio ratio="16:9">
                <Box
                  sx={{
                    backgroundColor: 'black',
                    height: '100%',
                    borderRadius: '10px',
                    transform: 'perspective(100em) rotateX(70deg)',
                  }}
                >
                </Box>
              </AspectRatio>
            </Box>
          </Box>
          <Grid
            sx={{
              gridTemplateColumns: ['repeat(1, 1fr)', 'repeat(2, 1fr)', 'repeat(4, 1fr)'],
              gap: 5,
            }}
          >
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Powered by React
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Configurable
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Extendible
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
            <Box>
              <Heading as="h3" size={1} mb={3} sx={{ fontWeight: 500, color: 'white' }}>
                Popular libraries
              </Heading>
              <Text as="p" size={3} sx={{ lineHeight: '2', color: 'gray600' }}>
                Built on top of Styled System Core. Styled-components. Modulz Styleguide provides fully-featured design system documentation for teams who need total control.
              </Text>
            </Box>
          </Grid>
        </Container>
      </Box>

      <Box py={9}>
        <Container size={3}>
          <Flex mt={8} sx={{ alignItems: 'center' }}>
            <Box mr={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <img
                src="/home/editor.png"
                style={{
                  display: 'block',
                  maxWidth: '100%',
                  boxShadow:
                    'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
                  borderWidth: '1px',
                  borderStyle: 'solid',
                  borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
                  borderRadius: '10px',
                }}
              />
            </Box>
            <Box ml={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <Heading as="h3" size={3} mb={3} sx={{ fontWeight: 500, letterSpacing: '-.042em' }}>
                Panes
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', letterSpacing: '-.008em' }}>
                This is going to be a bit of a thought dump, I'm not sure any of it blocks the registration itself, but
                I think it brings up a lot of questions.
              </Text>
            </Box>
          </Flex>

          <Flex mt={8} sx={{ alignItems: 'center' }}>
            <Box mr={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <img
                src="/home/editor.png"
                style={{
                  display: 'block',
                  maxWidth: '100%',
                  boxShadow:
                    'hsla(208, 28%, 12%, 0.42) 0px 60px 123px -25px, hsla(208, 25%, 10%, 0.08) 0px 35px 75px -35px',
                  borderWidth: '1px',
                  borderStyle: 'solid',
                  borderColor: 'hsl(208, 18%, 86%) hsl(208, 18%, 86%) hsl(210, 16%, 76%)',
                  borderRadius: '10px',
                }}
              />
            </Box>
            <Box ml={6} sx={{ flexBasis: '0', flexGrow: '1' }}>
              <Heading as="h3" size={3} mb={3} sx={{ fontWeight: 500, letterSpacing: '-.042em' }}>
                Transitions
              </Heading>
              <Text as="p" size={4} sx={{ lineHeight: '3', letterSpacing: '-.008em' }}>
                This is going to be a bit of a thought dump, I'm not sure any of it blocks the registration itself, but
                I think it brings up a lot of questions.
              </Text>
            </Box>
          </Flex>
        </Container>
      </Box>

      <Divider mx="auto" size={2} />

      <BetaAccess />
    </Box>
  );
};

export default Editor;
